DELETE FROM Review;
DELETE FROM ArtPiece;
DELETE FROM Museum;
DELETE FROM City;

INSERT INTO City VALUES ('PA', 'Paris', 13552517, 'France', 'French');
INSERT INTO City VALUES ('NY', 'New York', 8198291, 'United States', 'English');
INSERT INTO City VALUES ('CMX', 'Mexico City', 9222630, 'Mexico', 'Spanish');
INSERT INTO City VALUES ('MA', 'Madrid', 8632605, 'Spain', 'Spanish');
INSERT INTO City VALUES ('LO', 'London', 8495514, 'United Kingdom', 'English');
INSERT INTO City VALUES ('WA', 'Washington Dc ', 6851424, 'United States ', 'English');
INSERT INTO City VALUES ('AM', 'Amsterdam', 2769915, 'Netherlands', 'Dutch');
INSERT INTO City VALUES ('BE', 'Berlin', 12686448, 'Germany', 'German');
INSERT INTO City VALUES ('BI', 'Bilbao', 12531123, 'Spain', 'Spanish');
INSERT INTO City VALUES ('TO', 'Tokyo', 8361459, 'Japan', 'Japanese');
INSERT INTO City VALUES ('AT', 'Athens', 7009808, 'Greece', 'Greek');
INSERT INTO City VALUES ('RO', 'Rome', 14759900, 'Italy', 'Italian');
INSERT INTO City VALUES ('FL', 'Florence', 2042485, 'Italy', 'Italian');
INSERT INTO City VALUES ('SE', 'Seattle', 9946954, 'United States ', 'English');
INSERT INTO City VALUES ('LA', 'Los Angeles', 5341238, 'United States', 'English');
INSERT INTO City VALUES ('CAI', 'Cairo', 13001048, 'Egypt', 'Arabic');
INSERT INTO City VALUES ('SEO', 'Seoul', 14647143, 'South Korea', 'Korean');
INSERT INTO City VALUES ('BEI', 'Beijing', 7574139, 'China', 'Chinese');
INSERT INTO City VALUES ('MO', 'Moskow', 5114759, 'Russia', 'Russian');
INSERT INTO City VALUES ('LIV', 'Liverpool', 13485642, 'United Kingdom', 'English');
INSERT INTO City VALUES ('SP', 'Sao Paulo', 2214618, 'Brazil', 'Portuguese');
INSERT INTO City VALUES ('JO', 'Johannesburg', 13921273, 'South Africa ', 'English');
INSERT INTO City VALUES ('DE', 'Copenhagen', 11818910, 'Denmark', 'Danish');
INSERT INTO City VALUES ('ME', 'Melbourne', 5175263, 'Australia', 'English');
INSERT INTO City VALUES ('SY', 'Sydney', 12224183, 'Australia', 'English');
INSERT INTO City VALUES ('BA', 'Barcelona', 13477184, 'Spain', 'Spanish');
INSERT INTO City VALUES ('MON', 'Montreal', 8863484, 'Canada', 'English');
INSERT INTO City VALUES ('VA', 'Vancouver', 4557662, 'Canada', 'English');
INSERT INTO City VALUES ('BOS', 'Boston', 14787138, 'United States', 'English');

INSERT INTO Museum VALUES ('SI', 'Smithsonian Institution', '100 Main Street', 'Art', 'WA');
INSERT INTO Museum VALUES ('LL', 'Le Louvre', '101 Main Street', 'Science', 'PA');
INSERT INTO Museum VALUES ('TAMT', 'The Acropolis Museum', '102 Main Street', 'Children', 'AT');
INSERT INTO Museum VALUES ('TBMT', 'The British Museum', '103 Main Street', 'Art', 'LO');
INSERT INTO Museum VALUES ('TP', 'The Prado', '104 Main Street', 'Science', 'MA');
INSERT INTO Museum VALUES ('MOMA', 'The Metropolitan Museum Of Art', '105 Main Street', 'Children', 'NY');
INSERT INTO Museum VALUES ('TUGT', 'The Uffizi Gallery', '106 Main Street', 'Art', 'FL');
INSERT INTO Museum VALUES ('RI', 'Rijksmuseum', '107 Main Street', 'Science', 'AM');
INSERT INTO Museum VALUES ('AP', 'Apartheid Museum', '108 Main Street', 'Children', 'JO');
INSERT INTO Museum VALUES ('TMAT', 'The Museu De Arte', '109 Main Street', 'Art', 'SP');
INSERT INTO Museum VALUES ('TNTT', 'The National Art Center In Tokyo', '110 Main Street', 'Science', 'TO');
INSERT INTO Museum VALUES ('NMHN', 'National Museum Of African American History', '111 Main Street', 'Children', 'WA');
INSERT INTO Museum VALUES ('TM', 'Tate Modern', '112 Main Street', 'Art', 'LO');
INSERT INTO Museum VALUES ('MET', 'Met', '113 Main Street', 'Science', 'NY');
INSERT INTO Museum VALUES ('TMEAT', 'The Museum Of Egyptian Antiquities', '114 Main Street', 'Children', 'CAI');
INSERT INTO Museum VALUES ('MNAM', 'Museo Nacional De Antropología', '115 Main Street', 'Art', 'CMX');
INSERT INTO Museum VALUES ('MDO', 'Musée DOrsay', '116 Main Street', 'Science', 'PA');
INSERT INTO Museum VALUES ('CDC', 'Castillo De Chapultepec', '117 Main Street', 'Children', 'CMX');
INSERT INTO Museum VALUES ('TVMT', 'The Van Gogh Museum', '118 Main Street', 'Art', 'AM');
INSERT INTO Museum VALUES ('PM', 'Pergamon Museum', '119 Main Street', 'Science', 'BE');
INSERT INTO Museum VALUES ('TGCT', 'The Getty Center', '120 Main Street', 'Children', 'LA');
INSERT INTO Museum VALUES ('SNMS', 'Smithsonian National Air And Space Museum', '121 Main Street', 'Art', 'WA');
INSERT INTO Museum VALUES ('NGAN', 'National Gallery Of Art', '122 Main Street', 'Science', 'LO');
INSERT INTO Museum VALUES ('NHMN', 'National Children Museum', '123 Main Street', 'Children', 'NY');
INSERT INTO Museum VALUES ('NHMW', 'National Art Museum', '124 Main Street', 'Art', 'WA');
INSERT INTO Museum VALUES ('NHML', 'National History Museum', '125 Main Street', 'Science', 'LO');
INSERT INTO Museum VALUES ('NMANS', 'National Museum Of Modern And Contemporary Art', '126 Main Street', 'Children', 'SEO');
INSERT INTO Museum VALUES ('JM', 'Jewish Museum', '127 Main Street', 'Art', 'BE');
INSERT INTO Museum VALUES ('NGVN', 'National Gallery Of Victoria', '128 Main Street', 'Science', 'ME');

INSERT INTO ArtPiece VALUES (1, 'Mona Lisa', 'Leonardo DaVinci','painting', 1862, 'SI');
INSERT INTO ArtPiece VALUES (2, 'Last Supper', 'Leonardo DaVinci','sculpture', 1622, 'LL');
INSERT INTO ArtPiece VALUES (3, 'Starry Night', 'Vincent Van Gogh','other', 1695, 'TAMT');
INSERT INTO ArtPiece VALUES (4, 'Guernica', 'Pablo Picasso','painting', 1812, 'TBMT');
INSERT INTO ArtPiece VALUES (5, 'Impression Sunrise', 'Claude Monet','sculpture', 1986, 'TP');
INSERT INTO ArtPiece VALUES (6, 'Birth Of Venus', 'Sandro botticelli','other', 1745, 'MOMA');
INSERT INTO ArtPiece VALUES (7, 'David', 'Michelangelo','painting', 1878, 'TUGT');
INSERT INTO ArtPiece VALUES (8, 'Las Meninas', 'Diego Velazquez','sculpture', 1656, 'RI');
INSERT INTO ArtPiece VALUES (9, 'The Kiss', 'Leonardo DaVinci','other', 1922, 'RI');
INSERT INTO ArtPiece VALUES (10, 'Liberty Leading The People', 'Vincent Van Gogh','painting', 1642, 'TMAT');
INSERT INTO ArtPiece VALUES (11, 'The Scream', 'Pablo Picasso','sculpture', 1962, 'TNTT');
INSERT INTO ArtPiece VALUES (12, 'The Night Watch', 'Claude Monet','other', 1569, 'NMHN');
INSERT INTO ArtPiece VALUES (13, 'American Gothic', 'Sandro botticelli','painting', 1758, 'TM');
INSERT INTO ArtPiece VALUES (14, 'Cannes Soup', 'Michelangelo','sculpture', 1732, 'MET');
INSERT INTO ArtPiece VALUES (15, 'Venus Of Willendorf', 'Diego Velazquez','other', 1916, 'TMEAT');
INSERT INTO ArtPiece VALUES (16, 'Bust Of Nefertiti', 'Leonardo DaVinci','painting', 1917, 'MNAM');
INSERT INTO ArtPiece VALUES (17, 'Laocoon And His Sons', 'Vincent Van Gogh','sculpture', 1599, 'MDO');
INSERT INTO ArtPiece VALUES (18, 'Michelangelo', 'Pablo Picasso','other', 1808, 'CDC');
INSERT INTO ArtPiece VALUES (19, 'Antonio Canova', 'Claude Monet','painting', 1782, 'TVMT');
INSERT INTO ArtPiece VALUES (20, 'Girl With A Pearl Earring', 'Sandro botticelli','sculpture', 1609, 'PM');
INSERT INTO ArtPiece VALUES (21, 'Café Terrace At Night', 'Michelangelo','other', 1814, 'TGCT');
INSERT INTO ArtPiece VALUES (22, 'The Third Of May', 'Diego Velazquez','painting', 1843, 'SNMS');
INSERT INTO ArtPiece VALUES (23, 'Lady With An Ermine', 'Leonardo DaVinci','sculpture', 1803, 'NGAN');
INSERT INTO ArtPiece VALUES (24, 'The Raft Of The Medusa', 'Vincent Van Gogh','other', 1920, 'NHMN');
INSERT INTO ArtPiece VALUES (25, 'Napoleon Crossing The Alps', 'Pablo Picasso','painting', 1968, 'NHMW');
INSERT INTO ArtPiece VALUES (26, 'The Naked Maja', 'Claude Monet','sculpture', 1862, 'NHML');
INSERT INTO ArtPiece VALUES (27, 'The Creation Of Adam', 'Sandro botticelli','other', 1757, 'NMANS');
INSERT INTO ArtPiece VALUES (28, 'Irises', 'Michelangelo','painting', 1779, 'JM');
INSERT INTO ArtPiece VALUES (29, 'Paris Street In Rainy Weather', 'Diego Velazquez','sculpture', 1937, 'NGVN');
INSERT INTO ArtPiece VALUES (30, 'Boreas', 'Leonardo DaVinci','other', 1863, 'NGVN');

INSERT INTO Review VALUES (1, 'Edward Walmsley', 1, 'SI');
INSERT INTO Review VALUES (2, 'Amin Conway', 2, 'LL');
INSERT INTO Review VALUES (3, 'Giulia Wagner', 3, 'TAMT');
INSERT INTO Review VALUES (4, 'Zachery Crossley', 4, 'TBMT');
INSERT INTO Review VALUES (5, 'Malcolm Shaw', 5, 'TP');
INSERT INTO Review VALUES (6, 'Farrell Rodrigues', 1, 'MOMA');
INSERT INTO Review VALUES (7, 'Ema Burks', 2, 'TUGT');
INSERT INTO Review VALUES (8, 'Akshay Hutchinson', 3, 'RI');
INSERT INTO Review VALUES (9, 'Shahzaib York', 4, 'RI');
INSERT INTO Review VALUES (10, 'Rylee Hale', 5, 'TMAT');
INSERT INTO Review VALUES (11, 'Hazel Dotson', 1, 'TNTT');
INSERT INTO Review VALUES (12, 'Esmai Marks', 2, 'NMHN');
INSERT INTO Review VALUES (13, 'Hayleigh May', 3, 'TM');
INSERT INTO Review VALUES (14, 'Cory Weber', 4, 'MET');
INSERT INTO Review VALUES (15, 'Niamh Ireland', 5, 'TMEAT');
INSERT INTO Review VALUES (16, 'Aliya Kane', 1, 'MNAM');
INSERT INTO Review VALUES (17, 'Timothy Dixon', 2, 'MDO');
INSERT INTO Review VALUES (18, 'Desiree Partridge', 3, 'CDC');
INSERT INTO Review VALUES (19, 'Roza OBrien', 4, 'TVMT');
INSERT INTO Review VALUES (20, 'Daisie Wilks', 5, 'PM');
INSERT INTO Review VALUES (21, 'Arjun Pollard', 1, 'TGCT');
INSERT INTO Review VALUES (22, 'Gia Whitworth', 2, 'SNMS');
INSERT INTO Review VALUES (23, 'Lexie Read', 3, 'NGAN');
INSERT INTO Review VALUES (24, 'Carmel Redfern', 4, 'NHMN');
INSERT INTO Review VALUES (25, 'Jamila Vaughan', 5, 'NHMW');
INSERT INTO Review VALUES (26, 'Thierry Walls', 1, 'NHML');
INSERT INTO Review VALUES (27, 'Isla-Rae Frame', 2, 'NMANS');
INSERT INTO Review VALUES (28, 'Indigo Sanderson', 3, 'JM');
INSERT INTO Review VALUES (29, 'Lorenzo Kidd', 4, 'NGVN');
INSERT INTO Review VALUES (30, 'Solomon Stewart', 5, 'NGVN');
